export const PERMISSIONS = {
  QUESTION_CREATE: "QUESTION_CREATE",
  QUESTION_EDIT: "QUESTION_EDIT",
  QUIZ_CREATE: "QUIZ_CREATE",
  QUIZ_ATTEMPT: "QUIZ_ATTEMPT",
  ATTEMPT_VIEW_OWN: "ATTEMPT_VIEW_OWN",
  ATTEMPT_VIEW_ALL: "ATTEMPT_VIEW_ALL",
} as const;